version: '3'
services:
  mysql:
    image: mysql
    network_mode: host
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: security
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 2s
      retries: 10
  myapp:
    image: security-app:latest
    network_mode: host
    depends_on:
      mysql:
        condition: service_healthy
