version: '3'
services:
  mysql-security:
    image: mysql
#    network_mode: host
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: security
      MYSQL_TCP_PORT: 3307
    ports:
      - "3307:3307"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 2s
      retries: 10

  security:
    image: nazariybrynyarskiy/security-app:latest
#    network_mode: host
    ports:
      - "8088:8088"
    depends_on:
      mysql-security:
        condition: service_healthy

  gateway:
    image: nazariybrynyarskiy/gateway-app:latest
    #    network_mode: host
    ports:
      - "8000:8000"

  coordinator:
    image: nazariybrynyarskiy/coordinator-app:latest
    #    network_mode: host
    ports:
      - "8082:8082"

  mysql-product:
    image: mysql
    #    network_mode: host
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: productservice
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 2s
      retries: 10

  product:
    image: nazariybrynyarskiy/product-app:latest
    #    network_mode: host
    ports:
      - "8090:8090"
    depends_on:
      mysql-product:
        condition: service_healthy

  mysql-profile:
    image: mysql
    #    network_mode: host
    ports:
      - "3308:3308"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: profileservice
      MYSQL_TCP_PORT: 3308
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 2s
      retries: 10

  profile:
    image: nazariybrynyarskiy/profile-app:latest
    #    network_mode: host
    ports:
      - "8087:8087"
    depends_on:
      mysql-profile:
        condition: service_healthy

networks:
  default:
    external:
      name: it-cluster
