version: '3'
services:
  mysql:
    image: mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: security
    ports:
      - "3306:3306"
  myapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8088:8088"
    depends_on:
      - mysql
